services:
  - type: web
    name: cliks-server
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: CORS_ORIGIN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
