services:
  - type: web
    name: cliks-server
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cliks-db
          property: connectionString

databases:
  - name: cliks-db
    databaseName: cliks
    plan: free
    region: singapore
    postgresMajorVersion: "17"
